### ISSUE TITLE
Fix scrolling tabs

### ISSUE THREAD

**Issue by dimti** [Infocatcher/Tab_Scope_Tweaker#1]
Hi

I start to use Tab Scope two days ago. And i have bug - my tabs panel not scrolling tabs om mouse wheel after preview tab is opened.

Tab scope blocked scrolling my tabs on mouse wheel on tab tabs panel

Do you think, it possible fix it in your Tab Scope Tweaker?

**Comment by Infocatcher** [comment]
> my tabs panel not scrolling tabs om mouse wheel after preview tab is opened.

Hmm... many opened tabs and some tabs aren't visible? I can't reproduce. May be some conflict with another extension?

Also please report your issue here: https://github.com/gomita/tabscope/issues

**Comment by dimti** [comment]
Ага

Написал.

Вроде похожую задачу там нашел
